@startuml
'https://plantuml.com/sequence-diagram

class ToDoListApp {
    main()
    start()
}

class MainWindowControllers {}
class ListWindowControllers {}

javafx.Application <|-- ToDoListApp

ToDoListApp -- ListWindowControllers
ToDoListApp -- MainWindowControllers
@enduml